# NumPy Arrayleri Oluşturma

## Listelerden Array Oluşturmak

In [1]:
import numpy as np

np.array([12, 33, 4, 5])
a = np.array([12, 33, 4, 5])
a
type(a)

numpy.ndarray

In [2]:
np.array([3.14, 4, 5, 12.5])

array([ 3.14,  4.  ,  5.  , 12.5 ])

In [3]:
np.array([3.14, 4, 5, 12.5], dtype = 'float32')

array([ 3.14,  4.  ,  5.  , 12.5 ], dtype=float32)

In [4]:
np.zeros(10, dtype=int ) # sıfırdan oluşan bir vektör oluşturur

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((2, 3)) # birlerden oluşan 2ye 3lük bir matris oluşturur

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.full((2, 3), 9) # 9lardan oluşan 2ye 3lük bir matris oluşturur

array([[9, 9, 9],
       [9, 9, 9]])

In [7]:
np.arange(0, 10, 2) # 0'dan 10'a kadar 2'şer 2'şer atlayarak bir array oluşturur

array([0, 2, 4, 6, 8])

In [8]:
np.linspace(0, 1, 30) # 0 ile 1 arasında 30 adet sayı üretir (0 ile 1 dahildir.)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [9]:
np.random.normal(0, 1, (3, 4))

array([[ 0.52645391,  0.40717593, -1.84355937, -0.51604065],
       [ 1.38569495, -0.60336016, -2.27574963,  1.04320091],
       [ 0.93331459, -1.36170708, -0.21962453, -1.47281583]])

In [10]:
np.random.randint(0, 10, (2, 2))

array([[6, 7],
       [0, 1]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy Biçimlendirme

* **ndim** : boyut sayısı
* **shape** : boyut bilgisi
* **size** : toplam eleman sayısı
* **dtype** : array veri tipi

In [12]:
import numpy as np

a = np.random.randint(10, size=10)
a.ndim 

1

In [13]:
a.shape

(10,)

In [14]:
a.size

10

In [15]:
a.dtype

dtype('int32')

In [16]:
a = np.random.randint(0, 10, (4, 4))

In [17]:
a.ndim

2

In [18]:
a.shape

(4, 4)

In [19]:
a.size

16

In [20]:
a.dtype

dtype('int32')

# Reshape işlemleri

In [21]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
#np.arange(1, 9).reshape((3, 3))

In [24]:
a = np.array([1, 2, 3])

In [25]:
a

array([1, 2, 3])

In [26]:
b = a.reshape((1, 3))

In [27]:
b.ndim

2

In [28]:
a

array([1, 2, 3])

In [29]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [30]:
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Birleştirme İşlemleri

In [31]:
x = np.arange(1, 4)
y = np.arange(4, 7)

In [32]:
x

array([1, 2, 3])

In [33]:
y

array([4, 5, 6])

In [34]:
np.concatenate([x ,y])

array([1, 2, 3, 4, 5, 6])

In [35]:
z = [1, 2, 3]

In [36]:
np.concatenate([x ,y, z])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [37]:
a = np.arange(1, 7).reshape(2, 3)

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate([a ,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
np.concatenate([a ,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [41]:
# farklı boyutlu

In [42]:
a = np.arange(1, 4)

b = np.random.randint(1, 10, (2, 3))

In [43]:
a

array([1, 2, 3])

In [44]:
b

array([[6, 6, 4],
       [8, 5, 7]])

In [45]:
np.vstack([a, b])

array([[1, 2, 3],
       [6, 6, 4],
       [8, 5, 7]])

In [46]:
a = np.array([[99],
              [99]])

In [47]:
a

array([[99],
       [99]])

In [48]:
np.hstack([a, b])

array([[99,  6,  6,  4],
       [99,  8,  5,  7]])

# Ayırmak (splitting)

In [49]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

In [50]:
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [51]:
np.split(x, [3, 5]) # 3. ve 5. indekler

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [52]:
a, b, c = np.split(x, [3, 5])

In [53]:
a

array([1, 2, 3])

In [54]:
b

array([99, 99])

In [55]:
c

array([3, 2, 1])

In [56]:
a = np.arange(16).reshape(4, 4)

In [57]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
a, b = np.split(a, (2), axis=0)
b

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])

In [60]:
#ya da 

In [61]:
m = np.arange(16).reshape((4, 4))

In [62]:
ust, alt = np.vsplit(m, [2])

In [63]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
sol, sag = np.hsplit(m, [2])

In [66]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# SIRALAMAK

In [67]:
v = np.random.randint(0, 10, 5)

In [68]:
v

array([7, 9, 6, 2, 3])

In [69]:
np.sort(v)

array([2, 3, 6, 7, 9])

In [70]:
v

array([7, 9, 6, 2, 3])

In [71]:
v.sort()

In [72]:
v

array([2, 3, 6, 7, 9])

In [73]:
v = np.array([2, 1, 4, 3, 5])

In [74]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [75]:
i = np.argsort(v) #hangi index nereye gitti onu yazdırır

In [76]:
i

array([1, 0, 3, 2, 4], dtype=int64)

In [77]:
v

array([2, 1, 4, 3, 5])

In [78]:
v[i]

array([1, 2, 3, 4, 5])

# NumPy Eleman işlemleri 

In [79]:
import numpy as np
a = np.random.randint(10, size=10)
a

array([6, 9, 2, 6, 9, 1, 4, 7, 7, 1])

In [80]:
#tek boyutlu

In [81]:
a[0]

6

In [82]:
a[-1]

1

In [83]:
a[-2]

7

In [84]:
a = np.random.randint(10, size=(3, 5))

In [85]:
a

array([[3, 0, 2, 8, 4],
       [0, 5, 4, 1, 9],
       [2, 7, 6, 7, 9]])

In [86]:
a[0, 0]

3

In [87]:
a[1, 1]

5

In [88]:
a[0, 0] = 1

In [89]:
a

array([[1, 0, 2, 8, 4],
       [0, 5, 4, 1, 9],
       [2, 7, 6, 7, 9]])

In [90]:
a[1,1] = 2.2

In [91]:
a[1,1]

2

# slicing()

In [92]:
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [93]:
a[0:3]

array([20, 21, 22])

In [94]:
a[:3]

array([20, 21, 22])

In [95]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [96]:
a[::2]#sıfırdan başladı birer sayı atlayarak alır

array([20, 22, 24, 26, 28])

In [97]:
a[1::2] # tek sayılar

array([21, 23, 25, 27, 29])

In [98]:
a[2::2]#2.indeksten başlar ikişer ikişer gider

array([22, 24, 26, 28])

In [99]:
a[1::3]#1.indeksten başlar 3er 3er gider

array([21, 24, 27])

In [100]:
a = np.random.randint(10, size=(5, 5))

In [101]:
a

array([[5, 0, 5, 1, 1],
       [6, 0, 9, 0, 3],
       [9, 3, 4, 4, 2],
       [0, 4, 3, 2, 0],
       [4, 7, 4, 3, 2]])

In [102]:
a[:, 0]    

array([5, 6, 9, 0, 4])

In [103]:
a[:, 1]

array([0, 0, 3, 4, 7])

In [104]:
a[:, 4]

array([1, 3, 2, 0, 2])

In [105]:
a

array([[5, 0, 5, 1, 1],
       [6, 0, 9, 0, 3],
       [9, 3, 4, 4, 2],
       [0, 4, 3, 2, 0],
       [4, 7, 4, 3, 2]])

In [106]:
a[0,:]

array([5, 0, 5, 1, 1])

In [107]:
a[0]

array([5, 0, 5, 1, 1])

# Fancy Index ile Eleman İşlemleri

In [108]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [109]:
v[1]
v[3]

9

In [110]:
[v[1],
v[3]]

[3, 9]

In [111]:
al_getir = [1, 3, 5]

In [112]:
v[al_getir]

array([ 3,  9, 15])

In [113]:
m = np.arange(9).reshape((3, 3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [114]:
satir = np.array([0, 1])
sutun = np.array([1, 2])

In [115]:
m[satir, sutun]

array([1, 5])

In [116]:
m[0, [1, 2]]

array([1, 2])

In [117]:
m[0:, [1, 2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [118]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
index = np.array([0, 1, 2])
index

array([0, 1, 2])

In [120]:
v[index]

array([0, 1, 2])

In [121]:
v[index] = 99

In [122]:
v

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [123]:
v[[0, 1]] = [4,5]

In [124]:
v

array([ 4,  5, 99,  3,  4,  5,  6,  7,  8,  9])

# Koşullu Eleman İşlemleri

In [125]:
v = np.arange(1, 6)

In [126]:
v

array([1, 2, 3, 4, 5])

In [127]:
v>3

array([False, False, False,  True,  True])

In [128]:
v < 3

array([ True,  True, False, False, False])

In [129]:
v <= 3

array([ True,  True,  True, False, False])

In [130]:
v == 3

array([False, False,  True, False, False])

In [131]:
v != 3

array([ True,  True, False,  True,  True])

In [132]:
# İki Array'i karşılaştırma

In [133]:
(v ** 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [134]:
(2 * v) == (v ** 2)

array([False,  True, False, False, False])

In [135]:
# ufunc

np.equal

np.not_equal

np.less

np.less_equal

np.greater

np.greater_equal

# NumPy Hesaplamalı İşlemler

In [136]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [137]:
a - 1

array([-1,  0,  1,  2,  3])

In [138]:
a /2 

array([0. , 0.5, 1. , 1.5, 2. ])

In [139]:
a ** 2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [140]:
5*(a/2*9)

array([ 0. , 22.5, 45. , 67.5, 90. ])

In [141]:
np.add(a, 2)

array([2, 3, 4, 5, 6])

In [142]:
np.subtract(a, 1)

array([-1,  0,  1,  2,  3])

In [143]:
np.multiply(a, 3)

array([ 0,  3,  6,  9, 12])

In [144]:
np.divide(a,2)

array([0. , 0.5, 1. , 1.5, 2. ])

In [145]:
np.power(a, 3)

array([ 0,  1,  8, 27, 64], dtype=int32)

In [146]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [147]:
np.add.reduce(a)

15

In [148]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [149]:
np.mean(a)

3.0

# Farklı Boyutlu Arrayler ile Birlikte Çalışmak (Broadcasting)

In [150]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

a+b

array([2, 4, 6])

In [151]:
m = np.ones((3, 3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [152]:
a + m

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

# PANDAS

# **Pandas Series

In [153]:
import numpy as np
import pandas as pd

In [154]:
pd.Series([1, 2, 3, 4])

0    1
1    2
2    3
3    4
dtype: int64

In [155]:
seri = pd.Series([1, 2, 3, 4])

In [156]:
type(seri)

pandas.core.series.Series

In [157]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [158]:
seri.dtype

dtype('int64')

In [159]:
seri.empty

False

In [160]:
seri.ndim

1

In [161]:
seri.size

4

In [162]:
seri.values

array([1, 2, 3, 4], dtype=int64)

In [163]:
seri.head(2)

0    1
1    2
dtype: int64

In [164]:
seri[:3]

0    1
1    2
2    3
dtype: int64

In [165]:
seri.tail

<bound method NDFrame.tail of 0    1
1    2
2    3
3    4
dtype: int64>

In [166]:
seri.tail(2)

2    3
3    4
dtype: int64

In [167]:
a = np.array([1, 2, 3, 566, 88])

In [168]:
type(a)

numpy.ndarray

In [169]:
seri = pd.Series(a)

In [170]:
seri

0      1
1      2
2      3
3    566
4     88
dtype: int32

In [171]:
seri.index

RangeIndex(start=0, stop=5, step=1)

In [172]:
seri[0]

1

In [173]:
pd.Series([1, 5, 0.9, 34], index=[1, 3, 4, 5])

1     1.0
3     5.0
4     0.9
5    34.0
dtype: float64

In [174]:
seri = pd.Series([1, 5, 0.9, 34], index=['a', 'b', 'c', 'd'])

In [175]:
seri['a']

1.0

In [176]:
sozluk = {"reg":10, "loj":11, "cart":12}

In [177]:
sozluk

{'reg': 10, 'loj': 11, 'cart': 12}

In [178]:
seri = pd.Series(sozluk)

In [179]:
seri['reg']

10

In [180]:
seri["reg":"cart"]

reg     10
loj     11
cart    12
dtype: int64

In [181]:
pd.concat([seri, seri])

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

In [182]:
seri.append(seri)

reg     10
loj     11
cart    12
reg     10
loj     11
cart    12
dtype: int64

# Serilerde Eleman İşlemleri

In [183]:
a = np.array([1, 2, 3, 33, 55, 66])
seri = pd.Series(a)
seri

0     1
1     2
2     3
3    33
4    55
5    66
dtype: int32

In [184]:
seri[0]

1

In [185]:
seri[0:3]

0    1
1    2
2    3
dtype: int32

In [186]:
seri = pd.Series([121, 200, 150, 99], index=["reg", "loj", "cart", "rf"] ) 
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [187]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [188]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [189]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [190]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [191]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [192]:
"knn" in seri

False

In [193]:
"reg" in seri

True

In [194]:
seri["reg"]

121

In [195]:
seri[['rf', 'reg']]

rf      99
reg    121
dtype: int64

In [196]:
seri['rf'] = 125

In [197]:
seri

reg     121
loj     200
cart    150
rf      125
dtype: int64

In [198]:
seri['loj':'rf']

loj     200
cart    150
rf      125
dtype: int64

In [199]:
seri[0:2]

reg    121
loj    200
dtype: int64

In [200]:
seri = pd.Series([121, 200, 150, 99], index=["reg", "loj", "cart", "rf"] ) 
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [201]:
seri[(seri>125) & (seri < 200)]

cart    150
dtype: int64

In [202]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [203]:
#data[0] # !!!HATA!!!

In [204]:
data[1]

'a'

In [205]:
data[5]

'c'

In [206]:
data[1:3]

3    b
5    c
dtype: object

In [207]:
data[0:3]

1    a
3    b
5    c
dtype: object

In [208]:
# loc label based indexing, tanımlandığı şekli ile index yakalamak

In [209]:
data

1    a
3    b
5    c
dtype: object

In [210]:
data.loc[1]

'a'

In [211]:
# data.loc[2]

In [212]:
data.loc[0:4]

1    a
3    b
dtype: object

In [213]:
# iloc positional indexing, indexi sıfırlayarak yakalamak

In [214]:
data

1    a
3    b
5    c
dtype: object

In [215]:
data.iloc[0]

'a'

In [216]:
# data.iloc[5] #HATA

In [217]:
data.iloc[:3]

1    a
3    b
5    c
dtype: object

# PANDAS DataFrame Özellikleri ve Oluşturma

In [218]:
l = [1, 4, 577, 343]
l

[1, 4, 577, 343]

In [219]:
pd.DataFrame(l, columns=['degisken_ismi'])

degisken_ismi
0              1
1              4
2            577
3            343

In [220]:
df = pd.DataFrame(l, columns=['degisken_ismi'])

In [221]:
type(df)

pandas.core.frame.DataFrame

In [222]:
df.axes

[RangeIndex(start=0, stop=4, step=1), Index(['degisken_ismi'], dtype='object')]

In [223]:
df.shape

(4, 1)

In [224]:
df.ndim

2

In [225]:
df.size

4

In [226]:
df.values

array([[  1],
       [  4],
       [577],
       [343]], dtype=int64)

In [227]:
df.head(2)

degisken_ismi
0              1
1              4

In [228]:
df.tail(2)

degisken_ismi
2            577
3            343

In [229]:
a = np.arange(5)

In [230]:
a

array([0, 1, 2, 3, 4])

In [231]:
pd.DataFrame(a, columns=['degisken_ismi'])

degisken_ismi
0              0
1              1
2              2
3              3
4              4

In [232]:
m = np.arange(1, 10).reshape((3, 3))

In [233]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [234]:
df = pd.DataFrame(m, columns=['var1', 'var2', 'var3'])

In [235]:
df.columns = ('deg1', 'deg2', 'deg3')

In [236]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [237]:
df = pd.DataFrame(m, columns=['var1', 'var2', 'var3'], index = ['a', 'b', 'c'] )

In [238]:
df

var1  var2  var3
a     1     2     3
b     4     5     6
c     7     8     9

# DataFrame Eleman İşlemleri

In [239]:
s1 = np.random.randint(10, size= 5)
s2 = np.random.randint(10, size= 5)
s3 = np.random.randint(10, size= 5)

df = pd.DataFrame({"var1":s1, "var2":s2, "var3":s3})
df

var1  var2  var3
0     7     1     1
1     3     8     7
2     2     7     6
3     0     9     7
4     0     3     6

In [240]:
df[:1]

var1  var2  var3
0     7     1     1

In [241]:
df.index = ["a", "b", "c", "d", "e"]

In [242]:
df

var1  var2  var3
a     7     1     1
b     3     8     7
c     2     7     6
d     0     9     7
e     0     3     6

In [243]:
df["c":"e"]

var1  var2  var3
c     2     7     6
d     0     9     7
e     0     3     6

In [244]:
df.drop("a", axis=0)

var1  var2  var3
b     3     8     7
c     2     7     6
d     0     9     7
e     0     3     6

In [245]:
df

var1  var2  var3
a     7     1     1
b     3     8     7
c     2     7     6
d     0     9     7
e     0     3     6

In [246]:
df.drop("a", axis=0, inplace=True)

In [247]:
df

var1  var2  var3
b     3     8     7
c     2     7     6
d     0     9     7
e     0     3     6

In [248]:
l = ['b', 'c']

In [249]:
l

['b', 'c']

In [250]:
df.drop(l, axis=0)

var1  var2  var3
d     0     9     7
e     0     3     6

In [251]:
df

var1  var2  var3
b     3     8     7
c     2     7     6
d     0     9     7
e     0     3     6

In [252]:
'var1' in df

True

In [253]:
l = ["var1", 'var2', 'var4']

In [254]:
for i in l:print(i in df)

True
True
False


In [255]:
df['var1'] is df['var1']

True

In [256]:
df['var2']

b    8
c    7
d    9
e    3
Name: var2, dtype: int32

In [257]:
df.var1

b    3
c    2
d    0
e    0
Name: var1, dtype: int32

In [258]:
df[['var1', 'var2']]

var1  var2
b     3     8
c     2     7
d     0     9
e     0     3

In [259]:
l = ['var1', 'var2']

In [260]:
df[l]

var1  var2
b     3     8
c     2     7
d     0     9
e     0     3

In [261]:
df['var4'] = df['var1'] / df['var2']

In [262]:
df

var1  var2  var3      var4
b     3     8     7  0.375000
c     2     7     6  0.285714
d     0     9     7  0.000000
e     0     3     6  0.000000

In [263]:
df.drop('var4', axis=1, inplace=True)

In [264]:
df

var1  var2  var3
b     3     8     7
c     2     7     6
d     0     9     7
e     0     3     6

In [265]:
df.drop(l, axis=1)

var3
b     7
c     6
d     7
e     6

In [266]:
df

var1  var2  var3
b     3     8     7
c     2     7     6
d     0     9     7
e     0     3     6

# Gözlem ve Değişkenlere Birlikte Erişmek

In [267]:
s1 = np.random.randint(10, size= 5)
s2 = np.random.randint(10, size= 5)
s3 = np.random.randint(10, size= 5)

df = pd.DataFrame({"var1":s1, "var2":s2, "var3":s3})
df

var1  var2  var3
0     1     7     0
1     3     2     3
2     9     4     0
3     8     0     4
4     4     5     0

In [268]:
df.loc[:3] #0 ve 3 dahil

var1  var2  var3
0     1     7     0
1     3     2     3
2     9     4     0
3     8     0     4

In [269]:
df.iloc[:3] # 3 dahil değil

var1  var2  var3
0     1     7     0
1     3     2     3
2     9     4     0

In [270]:
df.iloc[0, 0]

1

In [271]:
df.iloc[:3, :2]

var1  var2
0     1     7
1     3     2
2     9     4

In [272]:
df.iloc[2:6, 1:3]

var2  var3
2     4     0
3     0     4
4     5     0

In [273]:
df.loc[:3, 'var3']

0    0
1    3
2    0
3    4
Name: var3, dtype: int32

In [274]:
df.loc[:3, 'var2':'var3']

var2  var3
0     7     0
1     2     3
2     4     0
3     0     4

In [275]:
df

var1  var2  var3
0     1     7     0
1     3     2     3
2     9     4     0
3     8     0     4
4     4     5     0

In [276]:
df.loc[df.var1>5, ['var1','var2']]

var1  var2
2     9     4
3     8     0

In [277]:
df.loc[df.var1>5, ['var1','var2']].values

array([[9, 4],
       [8, 0]])

# Birleştirme(Join) İşlemleri

In [278]:
s1 = np.random.randint(10, size= 5)
s2 = np.random.randint(10, size= 5)
s3 = np.random.randint(10, size= 5)

df1 = pd.DataFrame({"var1":s1, "var2":s2, "var3":s3})
df1

var1  var2  var3
0     7     2     3
1     8     3     7
2     0     4     1
3     9     3     9
4     9     7     8

In [279]:
df2 = df1 + 99
df2

var1  var2  var3
0   106   101   102
1   107   102   106
2    99   103   100
3   108   102   108
4   108   106   107

In [280]:
pd.concat([df1, df2])

var1  var2  var3
0     7     2     3
1     8     3     7
2     0     4     1
3     9     3     9
4     9     7     8
0   106   101   102
1   107   102   106
2    99   103   100
3   108   102   108
4   108   106   107

In [281]:
pd.concat([df1, df2], axis=1)

var1  var2  var3  var1  var2  var3
0     7     2     3   106   101   102
1     8     3     7   107   102   106
2     0     4     1    99   103   100
3     9     3     9   108   102   108
4     9     7     8   108   106   107

In [282]:
pd.concat([df1, df2], ignore_index=True)

var1  var2  var3
0     7     2     3
1     8     3     7
2     0     4     1
3     9     3     9
4     9     7     8
5   106   101   102
6   107   102   106
7    99   103   100
8   108   102   108
9   108   106   107

In [283]:
df2.columns = ['var1', 'var2', 'deg3']

In [284]:
df2

var1  var2  deg3
0   106   101   102
1   107   102   106
2    99   103   100
3   108   102   108
4   108   106   107

In [285]:
df1

var1  var2  var3
0     7     2     3
1     8     3     7
2     0     4     1
3     9     3     9
4     9     7     8

In [286]:
a = pd.concat([df1, df2])

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [287]:
a

deg3  var1  var2  var3
0    NaN     7     2   3.0
1    NaN     8     3   7.0
2    NaN     0     4   1.0
3    NaN     9     3   9.0
4    NaN     9     7   8.0
0  102.0   106   101   NaN
1  106.0   107   102   NaN
2  100.0    99   103   NaN
3  108.0   108   102   NaN
4  107.0   108   106   NaN

In [288]:
pd.isnull(a).sum()

deg3    5
var1    0
var2    0
var3    5
dtype: int64

In [289]:
pd.concat([df1, df2], join='inner') # inner ile kesişen değerler gelir

var1  var2
0     7     2
1     8     3
2     0     4
3     9     3
4     9     7
0   106   101
1   107   102
2    99   103
3   108   102
4   108   106

In [290]:
pd.concat([df1, df2], join_axes=[df1.columns])

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  """Entry point for launching an IPython kernel.


var1  var2  var3
0     7     2   3.0
1     8     3   7.0
2     0     4   1.0
3     9     3   9.0
4     9     7   8.0
0   106   101   NaN
1   107   102   NaN
2    99   103   NaN
3   108   102   NaN
4   108   106   NaN

# Aggregation ve Gruplama İşlemleri

In [291]:
import seaborn as sns

In [292]:
df = sns.load_dataset('planets')

In [293]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [294]:
df.shape

(1035, 6)

In [295]:
df.count()

method            1035
number            1035
orbital_period     992
mass               513
distance           808
year              1035
dtype: int64

In [296]:
df['mass'].count()

513

In [297]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [298]:
df['mass'].describe()

count    513.000000
mean       2.638161
std        3.818617
min        0.003600
25%        0.229000
50%        1.260000
75%        3.040000
max       25.000000
Name: mass, dtype: float64

In [299]:
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [300]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

# Gruplama İşlemleri

In [301]:
 df.groupby('method')

In [302]:
df.groupby('method')['orbital_period'].sum()

method
Astrometry                       1.262360e+03
Eclipse Timing Variations        4.276480e+04
Imaging                          1.418973e+06
Microlensing                     2.207500e+04
Orbital Brightness Modulation    2.127920e+00
Pulsar Timing                    3.671511e+04
Pulsation Timing Variations      1.170000e+03
Radial Velocity                  4.553151e+05
Transit                          8.377523e+03
Transit Timing Variations        2.393505e+02
Name: orbital_period, dtype: float64